# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Solid
email: info@solidproject.org
url: 'https://solidproject.org/'
twitter_username: project_solid
github_username: solid
repository: solid/solidproject.org

# Build settings
markdown: kramdown
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

kramdown:
  input: GFM
  # GitHub Pages only supports rouge for syntax highlighting:
  # https://github.blog/2016-02-01-github-pages-now-faster-and-simpler-with-jekyll-3-0/#the-highlight-zone
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
